server:
  port: 8761

spring:
  application:
    name: discoverservice

eureka:
  instance:
    appname: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://172.26.12.212:8761/eureka/